### ISSUE TITLE
Specifying account without role silently ignores account

### ISSUE THREAD

**Issue by kennethuil** [Cox-Automotive/terraform-provider-alks#130]
If you add a secondary provider like this:

```
provider "alks" {
  url = "https://alks.coxautoinc.com/rest"
  account = "you can put literally anything here including the word 'bogus'.  Putting a real account number does nothing useful"
# no role
  alias = "prod"
}
```

that provider will basically be a duplicate of your "primary" provider and associated resources will go into your "primary" account.  You will not get any kind of error.

**Comment by amagana3** [comment]
I know we've already discussed via Slack (see here: https://coxauto.slack.com/archives/C4C5MKVQ9/p1620849347450600), but for visibility and for future referencing I can give a brief summary before closing out.

This is intentional, if you're going to configure the provider with _only_ an account field (assuming there are no credentials in your terminal), then you will get back a 403. Same goes with just the role field and no account. The TL;DR on why nothing happens in your example is because the terminal had STS credentials, so the provider had a fallback to authenticate.

### So how does this work? What is the purpose?

Assume you have two provider blocks conveniently named: **provider A** and **provider B**. Provider A should be configured using STS credentials exported into your terminal. Now that Provider A is configured, you would then add an account / role combination to Provider B (which you have ACCESS to, this is key). There is then a lookup in Terraform to make sure you have access to the account / role specified, and if all is successful you've now got multiple accounts configured. Now you can reference Provider A or Provider B via an alias to perform creation / deletions on resources thus making account switching _much_ easier / more convenient. 

For more detailed explanation and example, see here: https://registry.terraform.io/providers/Cox-Automotive/alks/latest/docs#multiple-provider-configuration
