### ISSUE TITLE
Feature Request: Support import of existing roles into Terraform state

### ISSUE THREAD

**Issue by willtaylor** [Cox-Automotive/terraform-provider-alks#18]
I've had several instances where my Terraform state got out of sync with the roles provisioned by this provider and would have really liked to leverage `terraform import` and/or `terraform refresh` to recover.  Manual editing of the state would probably have resolved my issue, but it was easier at the time to simply delete and recreate the roles in question.

**Comment by brianantonelli** [comment]
See #17

**Comment by jantman** [comment]
I'm not sure I'd say this is actually a duplicate. It looks like #17 is talking about the "out of sync" issue, but it doesn't directly address import.

**Comment by amagana3** [comment]
I'm closing this issue as this was technically fixed here: https://github.com/Cox-Automotive/terraform-provider-alks/pull/115

There is ONE important caveat. Due to the way ALKS Core is designed, this `terraform import` command forces a delete / create so be careful using this command if you don't have to! I'd still recommend creating new roles and deleting old ones. :)
