### ISSUE TITLE
Support for automatic plugin installation

### ISSUE THREAD

**Issue by jcarlson** [Cox-Automotive/terraform-provider-alks#88]
Terraform 0.13 has been released and introduces the ability to automatically install third-party providers. 

The ALKS Terraform provider should support automatic installation.

https://www.hashicorp.com/blog/automatic-installation-of-third-party-providers-with-terraform-0-13/

**Comment by apottere** [comment]
We also ran into this while starting to update all of our terraform to 0.13.  It looks like there's a non-trivial process:
![](https://user-images.githubusercontent.com/1980504/90044016-029b5f80-dc9b-11ea-9847-979d0231c304.png)

However, TF 0.13 made including unregistered provides a lot more annoying - not only do you have to manually install the provider, you have to create a `required_providers` definition in each terraform project to reference it, AFAICT.  This isn't a huge deal, but we'll also have to rip all of them out once the plugin is officially supported...

**Comment by duckpuppy** [comment]
You don't have to rip them all out - I would argue that specifying all providers in the `required_providers` block is best practice. I'm not saying you CAN'T rip them all out once it's officially supported, but it's not required.

**Comment by apottere** [comment]
@duckpuppy ah, when I was upgrading some of our projects I didn't realize you could install local versions of `registry.terraform.io` providers that didn't exist on the registry yet, based on the error message I was getting - I thought you had to namespace them with a different url in `required_providers` (I was using `github.com/cox-automotive/alks`).  Turns out this works just fine:
```
terraform {
  required_providers {
    alks = {
      source  = "cox-automotive/alks"
      version = "1.4.3"
    }
  }
}
```
As long as `Library/Application\ Support/io.terraform/plugins/registry.terraform.io/cox-automotive/alks/1.4.3/darwin_amd64/terraform-provider-alks_v1.4.3` exists.

**Comment by amagana3** [comment]
Sorry for the wait, but here it is: https://registry.terraform.io/providers/Cox-Automotive/alks/latest

Closing as this has been resolved. 👍🏼
